apiVersion: v1
kind: Service
metadata:
  name: centos-service
spec:
  type: NodePort
  ports:
  - port: 30022
    name: ssh
    protocol: TCP
    targetPort: 30022
    nodePort: 30022
  selector:
    app: centos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos-deployment
spec:
  selector:
    matchLabels:
      app: centos
  replicas: 1
  template:
    metadata:
      labels:
        app: centos
    spec:
      volumes:
      - name: sys-fs-cgroup
        hostPath:
          path: /sys/fs/cgroup
      securityContext:
        runAsUser: 0
      containers:
      - name: centos
        image: registry.splab.pdsea.f5net.com:5000/centos:latest
        command: ["/usr/sbin/init"]
        volumeMounts:
        - mountPath: /sys/fs/cgroup
          name: sys-fs-cgroup
        securityContext:
          privileged: true
        ports:
        - containerPort: 30022