apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudify-deployment
  namespace: rstahl-test
  labels:
    app: cloudify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudify
  template:
    metadata:
      labels:
        app: cloudify
    spec:
      volumes:
      - name: sys-fs-cgroup
        hostPath:
          path: /sys/fs/cgroup
      securityContext:
        runAsUser: 0
      containers:
      - name: cloudify-620
        image: cloudifyplatform/premium-cloudify-manager-aio:6.2.0
        volumeMounts:
        - mountPath: /sys/fs/cgroup
          name: sys-fs-cgroup
        securityContext:
          privileged: true
        ports:
        - containerPort: 80
        - containerPort: 5671
        - containerPort: 53333
        - containerPort: 8000