apiVersion: v1
kind: Service
metadata:
  name: centos-service
spec:
  type: NodePort
  ports:
  - port: 30022
    name: ssh
    protocol: TCP
    targetPort: 30022
    nodePort: 30022
  selector:
    app: centos