apiVersion: v1
kind: Service
metadata:
  name: centos-service
  namespace: rstahl-test
spec:
  ports:
  - protocol: TCP
    port: 30022
    targetPort: 30022
  selector:
    app: centos
  clusterIP: 100.127.193.0
  type: LoadBalancer