apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox
  labels:
    app: netbox
spec:
  replicas: 2
  selector:
    matchLabels:
      run: netbox
  template:
    metadata:
      labels:
        run: netbox
    spec:
      containers:
      - name: ubuntu
        image: tstanley933/ubuntu-netbox:latest
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      securityContext:
            runAsUser: 0