apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: docker-registry
          image: registry:latest
          env:
            - name: REGISTRY_HTTP_ADDR
              value: ":5000"
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: "/var/lib/registry"
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: "/certs/registry.splab.pdsea.f5net.com.crt"
            - name: REGISTRY_HTTP_TLS_KEY
              value: "/certs/registry.splab.pdsea.f5net.com.key.pem"
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry Realm"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: "/auth/htpasswd"
          ports:
          - name: http
            containerPort: 5000
          volumeMounts:
          - name: image-store
            mountPath: "/var/lib/registry"
          - name: certs-vol
            mountPath: /certs
          - name: auth
            mountPath: /auth
      volumes:
        - name: image-store
          persistentVolumeClaim:
            claimName: images-pv-claim
        - name: certs-vol
          hostPath:
            path: /mnt/storage/cert
            type: Directory
        - name: auth
          hostPath:
            path: /mnt/storage/cert/auth
            type: Directory

---

kind: Service
apiVersion: v1
metadata:
  name: docker-registry
  namespace: default
  labels:
    app: docker-registry
spec:
  selector:
    app: docker-registry
  type: NodePort
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30008