apiVersion: v1
kind: PersistentVolume
metadata:
  name: images-pv-volume
  labels:
    type: local
spec:
  storageClassName: camel_storage_class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce