kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: netbox-claim
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox
  labels:
    app: netbox
spec:
  replicas: 1
  selector:
    matchLabels:
      run: netbox
  template:
    metadata:
      labels:
        run: netbox
    spec:
      containers:
      - name: ubuntu
        image: tstanley933/ubuntu-netbox:latest
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: Always
        volumeMounts:
          - name: nfs-pvc
            mountPath: "/mnt"        
      restartPolicy: Always
      volumes:
      - name: nfs-pvc
        persistentVolumeClaim:
          claimName: netbox-claim
      securityContext:
            runAsUser: 0