apiVersion: memsql.com/v1alpha1
kind: MemsqlCluster
metadata:
  name: memsql-cluster
spec:
  license: BDFhYjc4N2FjMTUxMTQ0MzY4NDMyZDlmOTI2MGQzOWQzYJzOYQAAAAAAAAAAAAAAAAswNAIYcJI83uo02d4z+e0M9Gs4mt8iYbEBnw9xAhhOTdGqDRQcZxkqa2B8f+vyNr0a7kz0S2cAAA==
  adminHashedPassword: "*9269A7C3F1676FD03A16E6542322FF39235229C3"
  nodeImage:
    repository: memsql/node
    tag: centos-7.5.8-12c73130aa

  redundancyLevel: 1

  serviceSpec:
    type: NodePort
    objectMetaOverrides:
      labels:
        custom: label
      annotations:
        custom: annotations

  aggregatorSpec:
    count: 1
    height: 0.5
    storageGB: 256
    storageClass: singlestore-nfs-storage

    objectMetaOverrides:
      annotations:
      optional: annotation
      labels:
        optional: label

  leafSpec:
    count: 5
    height: 0.5
    storageGB: 2048
    storageClass: singlestore-nfs-storage

    objectMetaOverrides:
      annotations:
        optional: annotation
      labels:
        optional: label

  globalVariables:
    allow_unsupported_filesystem: "ON"