apiVersion: memsql.com/v1alpha1
kind: MemsqlCluster
metadata:
  name: memsql-cluster
spec:
  license: BGUyZmI4MGQyMWFmZDQzODRiMDA5ODg0ZDM4OGVjYTRkUMvOYAAAAAAAAAAAAAAAAAkwNgIZAOv9Pv4ssKIFFjjSY3rsBqxKHSvokCvC9AIZAOsPjtYC2YFW6cQpJJ7k+cBQFA+LIM+L3Q==
  adminHashedPassword: "*9269A7C3F1676FD03A16E6542322FF39235229C3"
  nodeImage:
    repository: memsql/node
    tag: centos-7.3.4-d596a2867a

  redundancyLevel: 1

  serviceSpec:
    objectMetaOverrides:
      labels:
        custom: label
      annotations:
        custom: annotations

  aggregatorSpec:
    count: 1
    height: 0.5
    storageGB: 256
    storageClass: singlestore-nfs-storage

    objectMetaOverrides:
      annotations:
      optional: annotation
      labels:
        optional: label

  leafSpec:
    count: 5
    height: 0.5
    storageGB: 2048
    storageClass: singlestore-nfs-storage

    objectMetaOverrides:
      annotations:
        optional: annotation
      labels:
        optional: label

  globalVariables:
    allow_unsupported_filesystem: "ON"