apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        file /etc/coredns/espkube.db espkube.sas-esp.splab.pdsea.f5net.com {
          upstream
        }
        cache 30
        loop
        reload
        loadbalance
    }
  espkube.db: |-
    ; espkube.sas-esp.splab.pdsea.f5net.com
    espkube.sas-esp.splab.pdsea.f5net.com.                   IN          SOA         sns.dns.icann.org.  noc.dns.icann.org. 2019101701 7200 3600 1209600 3600
    espkube.sas-esp.splab.pdsea.f5net.com.                   IN          NS          b.iana-servers.net.
    espkube.sas-esp.splab.pdsea.f5net.com.                   IN          NS          b.iana-servers.net.
    espkube.sas-esp.splab.pdsea.f5net.com.                   IN          A           10.10.2.38
    x06e99a32f02ead54c858311008ba089b.espkube.sas-esp.splab.pdsea.f5net.com.                   IN          A           10.10.2.38
    x0f7f6db696629450623f8b5e401d44a1.espkube.sas-esp.splab.pdsea.f5net.com.                   IN          A           10.10.2.38
    x756ba118a0549876f54bb226f7e47505.espkube.sas-esp.splab.pdsea.f5net.com.                   IN          A           10.10.2.38
    *                                                        IN          CNAME       espkube.sas-esp.splab.pdsea.f5net.com.
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"coredns","namespace":"kube-system","creationTimestamp":null},"data":{"Corefile":".:53 {\n    errors\n    health {\n       lameduck 5s\n    }\n    ready\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n       pods insecure\n       fallthrough in-addr.arpa ip6.arpa\n       ttl 30\n    }\n    prometheus :9153\n    forward . /etc/resolv.conf {\n       max_concurrent 1000\n    }\n    file /etc/coredns/espkube.db espkube.sas-esp.splab.pdsea.f5net.com {\n      upstream\n    }\n    cache 30\n    loop\n    reload\n    loadbalance\n}\n","espkube.db":"; espkube.sas-esp.splab.pdsea.f5net.com\nespkube.sas-esp.splab.pdsea.f5net.com.                   IN          SOA         sns.dns.icann.org.  noc.dns.icann.org. 2019101701 7200 3600 1209600 3600\nespkube.sas-esp.splab.pdsea.f5net.com.                   IN          NS          b.iana-servers.net.\nespkube.sas-esp.splab.pdsea.f5net.com.                   IN          NS          b.iana-servers.net.\nespkube.sas-esp.splab.pdsea.f5net.com.                   IN          A           10.144.184.84\n*                                                        IN          CNAME"}}
  creationTimestamp: null
  name: coredns
  namespace: kube-system
